# Generated by Django 4.2 on 2023-05-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
