# Generated by Django 4.2 on 2023-05-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='link',
        ),
    ]
