# Generated by Django 4.2 on 2023-05-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_room_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
